"""add RunResult and RunArtifacts tables

Revision ID: b7de53cddcf2
Revises: f47c3c0bb6cb
Create Date: 2025-07-24 16:26:33.740927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7de53cddcf2'
down_revision: Union[str, None] = 'f47c3c0bb6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_config_id', sa.Integer(), nullable=True),
    sa.Column('plot_comparison', sa.String(), nullable=True),
    sa.Column('plot_rewards', sa.String(), nullable=True),
    sa.Column('plot_tail_dist', sa.String(), nullable=True),
    sa.Column('plot_pie_weights', sa.String(), nullable=True),
    sa.Column('best_worst_40', sa.String(), nullable=True),
    sa.Column('best_worst_60', sa.String(), nullable=True),
    sa.Column('best_worst_80', sa.String(), nullable=True),
    sa.Column('account_value_csv', sa.String(), nullable=True),
    sa.Column('actions_csv', sa.String(), nullable=True),
    sa.Column('rewards_csv', sa.String(), nullable=True),
    sa.Column('weights_csv', sa.String(), nullable=True),
    sa.Column('stats_csv', sa.String(), nullable=True),
    sa.Column('config_json', sa.String(), nullable=True),
    sa.Column('log_file', sa.String(), nullable=True),
    sa.Column('archive_zip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_config_id'], ['run_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_config_id')
    )
    op.create_index(op.f('ix_run_artifacts_id'), 'run_artifacts', ['id'], unique=False)
    op.create_table('run_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_config_id', sa.Integer(), nullable=True),
    sa.Column('cumulative_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('final_portfolio_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_config_id'], ['run_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_config_id')
    )
    op.create_index(op.f('ix_run_results_id'), 'run_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_results_id'), table_name='run_results')
    op.drop_table('run_results')
    op.drop_index(op.f('ix_run_artifacts_id'), table_name='run_artifacts')
    op.drop_table('run_artifacts')
    # ### end Alembic commands ###