"""create run config model~

Revision ID: f47c3c0bb6cb
Revises: d0ba45b56d12
Create Date: 2025-07-22 16:22:19.402604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47c3c0bb6cb'
down_revision: Union[str, None] = 'd0ba45b56d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_value', sa.Float(), nullable=False),
    sa.Column('max_shares', sa.Integer(), nullable=False),
    sa.Column('rebalance_window', sa.Integer(), nullable=False),
    sa.Column('validation_window', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=False),
    sa.Column('train_end', sa.Date(), nullable=False),
    sa.Column('trade_start', sa.Date(), nullable=False),
    sa.Column('trade_end', sa.Date(), nullable=False),
    sa.Column('model_names', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_configs_id'), 'run_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_configs_id'), table_name='run_configs')
    op.drop_table('run_configs')
    # ### end Alembic commands ###